config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get '/secret', to: 'pages#secret', as: :secret

  devise_for :users, controllers: {sessions: 'users/sessions'}
  resources :users
  resources :reviews
  resources :photographers
  resources :pictures
  resources :portfolios

  root to: 'pages#home'

end

app/models/photographer.rb
class Photographer < ActiveRecord::Base
	belongs_to :user
	has_many :received_reviews, class_name: "Review", foreign_key: "reviewee_id"
	has_many :clients, class_name: "User", foreign_key: "client_id"
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  before_action :set_photographer, only: [:show, :edit, :update, :destroy]

  # GET /photographers
  # GET /photographers.json
  def index
    @photographers = Photographer.all
  end

  # GET /photographers/1
  # GET /photographers/1.json
  def show
  end

  # GET /photographers/new
  def new
    @photographer = Photographer.new
  end

  # GET /photographers/1/edit
  def edit
  end

  # POST /photographers
  # POST /photographers.json
  def create
    @photographer = Photographer.new(photographer_params)

    respond_to do |format|
      if @photographer.save
        format.html { redirect_to @photographer, notice: 'Photographer was successfully created.' }
        format.json { render :show, status: :created, location: @photographer }
      else
        format.html { render :new }
        format.json { render json: @photographer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photographers/1
  # PATCH/PUT /photographers/1.json
  def update
    respond_to do |format|
      if @photographer.update(photographer_params)
        format.html { redirect_to @photographer, notice: 'Photographer was successfully updated.' }
        format.json { render :show, status: :ok, location: @photographer }
      else
        format.html { render :edit }
        format.json { render json: @photographer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photographers/1
  # DELETE /photographers/1.json
  def destroy
    @photographer.destroy
    respond_to do |format|
      format.html { redirect_to photographers_url, notice: 'Photographer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photographer
      @photographer = Photographer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photographer_params
      params.require(:photographer).permit(:description, :extras, :pricing)
    end
end

app/helpers/photographers_helper.rb
module PhotographersHelper
end

app/views/photographers/_form.html.erb
<%= form_for(@photographer) do |f| %>
  <% if @photographer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photographer.errors.count, "error") %> prohibited this photographer from being saved:</h2>

      <ul>
      <% @photographer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :extras %><br>
    <%= f.text_area :extras %>
  </div>
  <div class="field">
    <%= f.label :pricing %><br>
    <%= f.text_area :pricing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photographers/edit.html.erb
<h1>Editing Photographer</h1>

<%= render 'form' %>

<%= link_to 'Show', @photographer %> |
<%= link_to 'Back', photographers_path %>

app/views/photographers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photographers</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Extras</th>
      <th>Pricing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photographers.each do |photographer| %>
      <tr>
        <td><%= photographer.description %></td>
        <td><%= photographer.extras %></td>
        <td><%= photographer.pricing %></td>
        <td><%= link_to 'Show', photographer %></td>
        <td><%= link_to 'Edit', edit_photographer_path(photographer) %></td>
        <td><%= link_to 'Destroy', photographer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photographer', new_photographer_path %>

app/views/photographers/new.html.erb
<h1>New Photographer</h1>

<%= render 'form' %>

<%= link_to 'Back', photographers_path %>

app/views/photographers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @photographer.description %>
</p>

<p>
  <strong>Extras:</strong>
  <%= @photographer.extras %>
</p>

<p>
  <strong>Pricing:</strong>
  <%= @photographer.pricing %>
</p>

<%= link_to 'Edit', edit_photographer_path(@photographer) %> |
<%= link_to 'Back', photographers_path %>